<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="TYSS-ELF-Manjunath" ignored="0" name="RetryFailedTestScripts" tests="5" failures="1" timestamp="30 May 2020 07:15:37 GMT" time="25.207" errors="0">
  <testcase name="LoginVerify" time="6.892" classname="scripts.TestScripts">
    <skipped/>
  </testcase> <!-- LoginVerify -->
  <testcase name="LoginVerify" time="5.981" classname="scripts.TestScripts">
    <skipped/>
  </testcase> <!-- LoginVerify -->
  <testcase name="LoginVerify" time="6.047" classname="scripts.TestScripts">
    <skipped/>
  </testcase> <!-- LoginVerify -->
  <testcase name="LoginVerify" time="6.069" classname="scripts.TestScripts">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at scripts.TestScripts.LoginVerify(TestScripts.java:26)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- LoginVerify -->
  <testcase name="homeVerify" time="0.191" classname="scripts.TestScripts"/>
</testsuite> <!-- RetryFailedTestScripts -->
